[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.1.0" }
protobuf = { id = "com.google.protobuf", version = "0.9.5" }

[libraries]
grpc-protobuf = { group = "io.grpc", name = "grpc-protobuf", version = "1.78.0" }
grpc-netty = { group = "io.grpc", name = "grpc-netty", version = "1.78.0" }

protoc = { group = "com.google.protobuf", name = "protoc", version = "4.33.3" }

protobuf-kotlin = { group = "com.google.protobuf", name = "protobuf-kotlin", version = "4.33.4" }
protoc-gen-grpc-kotlin = { group = "io.grpc", name = "protoc-gen-grpc-kotlin", version = "1.4.1" }
protoc-gen-grpc-java = { group = "io.grpc", name = "protoc-gen-grpc-java", version = "1.62.2" }
grpc-testing = { group = "io.grpc", name = "grpc-testing", version = "1.78.0"}
grpc-stub = { group = "io.grpc", name = "grpc-stub", version = "1.78.0" }
grpc-kotlin-stub = { group = "io.grpc", name = "grpc-kotlin-stub", version = "1.4.1" }

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "1.10.2" }

[versions]
protobuf = "4.28.3"
grpc = "1.62.2"